---
kind: pipeline
type: docker
name: publish-lua

steps:
  - name: lua5.1
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.1'
      dockerfile: lua/5.1/Dockerfile
      dry_run: true

  - name: lua5.2
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.2'
      dockerfile: lua/5.2/Dockerfile
      dry_run: true

  - name: lua5.3
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.3'
      dockerfile: lua/5.3/Dockerfile
      dry_run: true

  - name: lua5.4
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.4'
      dockerfile: lua/5.4/Dockerfile
      dry_run: true

---
kind: pipeline
type: docker
name: publish-luarocks

steps:
  - name: luarocks 5.1
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.1'
      dockerfile: luarocks/5.1/Dockerfile
      dry_run: true

  - name: lua5.2
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.2'
      dockerfile: luarocks/5.2/Dockerfile
      dry_run: true

  - name: lua5.3
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.3'
      dockerfile: luarocks/5.3/Dockerfile
      dry_run: true

  - name: lua5.4
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.4'
      dockerfile: luarocks/5.4/Dockerfile
      dry_run: true
